### ISSUE TITLE
not working // RESOLVED

### ISSUE THREAD

**Issue by svpi11** [jnsgruk/wireguard-over-wss#7]
I'm having trouble realizing your tutorial now. Is it still up to date ? I'm doing all the steps you describe, but then my wireguard interface can load correctly, but cannot work properly (no transfer of data, and a basic command as 'curl' just freeze).
Any advice, way to debugg it ?

**Comment by jnsgruk** [comment]
Can you post some more information? Do you have any logs from the server side - from the `wstunnel` service or otherwise?

Are you able to connect on port 443 to the server from the client with something like `nc -v <server ip> 443`?

Can you post the output of `wg` and `wg showconf` on both sides?/

**Comment by svpi11** [comment]
Thanks for your answer, and above all sorry for my very LATE answer... lol.

I've tried it again recently and it now works perfectly. Thanks a lot for your work.
I don't know what I was doing before, but probably misconfigured something.

So thanks again ! ;)
